server:
  port: 8081

spring:
  application:
    name: smart-campus-api

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/smartcampus}
      database: smartcampus

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

app:
  jwt:
    secret: ${JWT_SECRET}   
    refresh-expiration: 604800000

  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

  upload:
    dir: ${UPLOAD_DIR:uploads}
    max-images-per-ticket: 3

logging:
  level:
    com.smartcampus: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
